### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jez** [bezi/a16zhack#1]
This is a list of things that still need to be done. Since there are so many of them, I wanted to create a single task list as opposed to individual issues. Feel free to check them off as they get done.

When all are checked, we can publicize!

### Frontend
- [x] Implement login screen
- [x] Display login screen if unauthenticated
- [x] Add logout button
- [x] Implement modal for entering new snapshot name
- [ ] Implement flash messages for errors
- [x] Pretty-print dates
- [x] "About" page
- [x] Listen to `'add-snapshot'` in PlaylistList (currently a bug)

### Deployment
- [x] Factor out config variables into environment variables
- [x] Get new API keys after, and put them into the _environment_

### Spotify
- [x] Investigate how collaborative playlists work
- [x] Get URL to profile picture

Feel free to add any more TODOs that you'd like. This might be my first hackathon project that ends up getting polished!

/cc @bezi @justingallagher

**Comment by bezi** [comment]
I dunno if you realize, but all of the config variables are indeed in ENV
variables (we set up different deploy keys, etc).  Check config.coffee.  We
also have different API keys.

I'll look into the collaborative playlists, it shouldn't be /too/ hard. :)

Oscar Bezi
oscar.bezi@gmail.com

**Comment by bezi** [comment]
I'd like to leave the default dev keys in for ease of development

**Comment by jez** [comment]
I'm actually developing with a local mongo instance. It's super easy to get
up and running.

**Comment by bezi** [comment]
Great!  You can have that in your environment variables ;)

It's not too hard, but it's easier to repro and debug things if the application works out of the box.  We can discuss this, but I'm all for having development keys checked in because A) we can always invalidate them and B) then the app will straight up work out of the box (yay for Mongo-as-a-Service.

**Comment by jez** [comment]
I disagree on basically all points.

- "Out of the box" you're stuck with someone else's development data. Whether your local setup works now depends on the state of a shared, constantly mutating database.
- Any sort of app keys checked into source control is an anti-pattern
  - This is especially worrisome when you consider that (I'm pretty sure) we're storing Spotify access_tokens there.
- It makes it harder for individuals to work separately (for example, I'd have to ask whoever has access to the development database when I want to drop it).

If it's all the same to you, I'm going to change it to prefer a local Mongo database once I've finished working on all the other things outlined above.

**Comment by jez** [comment]
So I investigated Spotify playlists again.

It actually works for collaborative playlists (playlists between you and your friends).
It doesn't work for official playlists that you can follow.

Any ideas why these would be different in the API?

**Comment by jez** [comment]
I decided not to implement flash messages, and collaborative playlists work (it's public playlists that don't), so I'm closing this.
